### ISSUE TITLE
API misuse in instruction translation

### ISSUE THREAD

**Issue by Phantom1003** [plctlab/plct-qemu#10]
In K set extension implement, when translate instruction, you'd better not directly using elements in cpu_gpr, because cpu_gpr[0] is not actually allocated, using gen_get_gpr instead
This code will trigger a segment fault when source register is $zero
https://github.com/isrc-cas/plct-qemu/blob/plct-k-dev/target/riscv/insn_trans/trans_rvk.c.inc#L65

**Comment by liweiwei90** [comment]
@Phantom1003 Thanks for your suggestion. This bug have been fixed when  Lucas rebased to support  v0.9.2.
