### ISSUE TITLE
有没有办法加速下QEMU中通过TCP/ssh进行scp操作的速度

### ISSUE THREAD

**Issue by lazyparser** [plctlab/plct-qemu#7]
Hi

由于做V8项目的测试需要，启动了QEMU/RISCV64/Fedora，用scp来将需要测试的程序copy进入VM，问题是大小有36GB。而我观察到运行scp速度最大被限定了 10M/s

有什么技巧或者参数可以加快copy的速度么？ or 需要让QEMU VM停下来，mount cp 才能得到更好的速度？

**Comment by liweiwei90** [comment]
可以考虑通过共享文件夹的方式来使用文件，大体的步骤如下：

**Comment by liweiwei90** [comment]
尝试了一下riscv virt machine上是可以和fedora共享文件的，大体流程是：
1）查看qemu版本是否支持virtio-9p-pci设备（qemu-system-riscv64 -device help | grep 9p），如果不支持可能需要重新编译qemu，在编译qemu configure时加上--enable-virtfs选项（可能还需要使能一些依赖库，如libcap-ng，使用--enable-cap-ng选项）;
2）运行qemu启动系统时加上-virtfs命令，如 -virtfs local,path=<share-dir-path>,mount_tag=<mount-name>,security_model=passthrough;
3）进入系统后采用9p格式加载共享文件夹，如mount <mount-name> -t 9p /mnt

**Comment by lazyparser** [comment]
不再成为问题。
